### ISSUE TITLE
Link to 3.11 documentation

### ISSUE THREAD

**Issue by adelton** [validatedpatterns/docs#336]
Page https://validatedpatterns.io/patterns/multicloud-gitops/mcg-cluster-sizing/ links to 3.11 documentation in the

> [System and environment requirements](https://docs.openshift.com/container-platform/3.11/install/prerequisites.html#hardware).

link. Based on https://access.redhat.com/support/policy/updates/openshift_noncurrent the 3.11 has been out of full support since June 2022.

A more contemporary OCP documentation should likely be linked.

**Comment by mbaldessari** [comment]
@abhatt-rh I looked around and could not find a single unique link covering minimum requirements for 4.13. There are specific ones like. Maybe https://docs.openshift.com/container-platform/4.13/architecture/architecture-installation.html#supported-platforms-for-openshift-clusters_architecture-installation ? Any better suggestions?

**Comment by abhatt-rh** [comment]
> @abhatt-rh I looked around and could not find a single unique link covering minimum requirements for 4.13. There are specific ones like. Maybe https://docs.openshift.com/container-platform/4.13/architecture/architecture-installation.html#supported-platforms-for-openshift-clusters_architecture-installation ? Any better suggestions?

Originally we had a table of HW requirements that was closer to the 3.11 requirements. When we updated these sections for MCG, I saw that those older requirements were picked from the [Source cluster section](https://docs.openshift.com/container-platform/4.13/migrating_from_ocp_3_to_4/premigration-checklists-3-4.html#source-cluster_premigration-checklists-3-4:~:text=minimum%20hardware%20requirements.) and hence the link. 

We can use [this](https://docs.openshift.com/container-platform/4.14/installing/installing_bare_metal/installing-bare-metal.html#minimum-resource-requirements_installing-bare-metal), which uses bare-metal as an example. Again, this pulled from the [Target cluster section](https://docs.openshift.com/container-platform/4.14/migrating_from_ocp_3_to_4/premigration-checklists-3-4.html#target-cluster_premigration-checklists-3-4:~:text=cluster%20meets%20the-,minimum%20hardware%20requirements,-for%20the%20specific) of the latest OpenShift docs. 

As far as generic links go, you are right that there's no generic HW requirements link in OpenShift docs. They are all platform-specific. Maybe we could add a statement in our docs :

> OpenShift cluster requirements vary for different platforms. See [OpenShift Container Platform documentation](https://docs.openshift.com/container-platform/4.13/installing/installing-preparing.html) for your platform-specific requirements.
