### ISSUE TITLE
An example output is the following -- no command given

### ISSUE THREAD

**Issue by adelton** [validatedpatterns/docs#345]
The page https://validatedpatterns.io/learn/vault/ says:

> 1. Inside the cluster directly when the helm value clusterGroup.insecureUnsealVaultInsideCluster is set to true. With this method a cronjob will run every five minutes inside the imperative namespace and unseal, initialize and configure the vault. The vault’s unseal keys and root token will be stored inside a secret called vaultkeys in the imperative namespace. It is considered best practice to copy the content of that secret offline, store it securely and then delete it.
> [...]
> An example output is the following:
> [...]

However, it is not clear output of what is meant here.

Is it
```
oc get -o jsonpath='{.data.vault_data_json}' -n imperative secret/vaultkeys | base64 -d -
```
which should be run, or something else?

Also, that

> It is considered best practice to copy the content of that secret offline, store it securely and then delete it.

part -- does that mean that the recommendation is to do
```
oc get -o yaml -n imperative secret/vaultkeys > secret-directory/vaultkeys.yaml
# backup secret-directory somehow
oc delete -n imperative secret/vaultkeys
```
? Or should that exported file `secret-directory/vaultkeys.yaml` be deleted?

**Comment by mbaldessari** [comment]
So the first part I think I addressed via https://github.com/validatedpatterns/docs/pull/358 (I added the full command). Let me clarify the second part in a PR. And yes the recommendation is to store the full content of the secret, store it securely somewhere and then delete it. Thanks for the suggestion, it makes sense
