### ISSUE TITLE
Help & Feedback yields Content unavailable

### ISSUE THREAD

**Issue by adelton** [validatedpatterns/docs#346]
Pages like https://validatedpatterns.io/patterns/industrial-edge/ or https://validatedpatterns.io/patterns/multicloud-gitops/ have in the *Links* line of the top frame link **Help & Feedback** with URL https://groups.google.com/g/hybrid-cloud-patterns.

Clicking that link produces
> Content unavailable
> [Click here to try again.](https://groups.google.com/g/hybrid-cloud-patterns)
> If you've seen this page more than once, try [switching accounts](https://accounts.google.com/AccountChooser?continue=https://groups.google.com/g/hybrid-cloud-patterns&faa=1).

I've tried it with various accounts.

**Comment by mbaldessari** [comment]
Meh, there has been a group rename and not all docs were updated. Thanks for the heads up!
