### ISSUE TITLE
Is the Seldon issue still an issue?

### ISSUE THREAD

**Issue by adelton** [validatedpatterns/docs#353]
The page https://validatedpatterns.io/patterns/industrial-edge/ has a Note

> Industrial Edge on OpenShift Container Platform 4.12 fails CI due to a Seldon issue. This only affects the Anomaly Detection AI/ML portion of the pattern. The rest of the pattern functions as designed. For more information on the Seldon issue, see https://github.com/SeldonIO/seldon-core/issues/4339.

However, that https://github.com/SeldonIO/seldon-core/issues/4339 has been marked resolved since 2023-03-08. Is the Note still valid?

**Comment by mbaldessari** [comment]
@claudiol Is the 4.12 note in the docs, current? I thought the issue around seldon was on 4.13 and onwards due to them locking the supported versions down https://github.com/redhat-openshift-ecosystem/community-operators-prod/blob/main/operators/seldon-operator/1.16.0/metadata/annotations.yaml#L16 ?

**Comment by claudiol** [comment]
So the note on the 4.12 docs is not current.  The community Seldon operator (v1.16.0) is available in OLM but it is not on > 4.13 afaik.  We will need to update the note in the docs.

**Comment by claudiol** [comment]
@adelton There is a Seldon operator in the certified-operators that should work with the Industrial Edge pattern.  I will test this and update this issue.

Seldon Operator
1.16.0-0 provided by Seldon Technologies

**Comment by claudiol** [comment]
@adelton I just tested the certified seldon-operator on 4.13 and it works.  There is a change in the values-datacenter.yaml that needs to look as follows:
```
    seldon-prod-dev:
      name: seldon-operator-certified
      namespaces: 
      - openshift-operators
      source: certified-operators
```

**Comment by mbaldessari** [comment]
@claudiol now that https://github.com/validatedpatterns/docs/pull/359 and https://github.com/validatedpatterns/industrial-edge/pull/233 merged, is it okay to close this one?
